name: BAK Github Action

on:
  push:
    branches: 'develop'

jobs:
  code_build_and_merge:
    name: code build
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      JWT_HEADER: ${{ secrets.JWT_HEADER }}
      JWT_PREFIX: ${{ secrets.JWT_PREFIX }}
      JWT_ACCESS_TOKEN_EXP: ${{ secrets.JWT_ACCESS_TOKEN_EXP }}
      JWT_REFRESH_TOKEN_EXP: ${{ secrets.JWT_REFRESH_TOKEN_EXP }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK Set up to 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'gradle'

      - name: gradlew
        run: chmod +x gradlew

      - name: Build gradle
        run: ./gradlew build --warning-mode=all

      - name: Git change branch to main
        run: git switch main

      - name: Git merge 'develop' to 'main'
        run: git merge develop